### ISSUE TITLE
Stop using OpenGraph and just use database columns for connector metadata

### ISSUE THREAD

**Issue by jshearer** [estuary/animated-carnival#58]
**Questions:**
* What metadata fields do we want/do we use? I found [this](https://github.com/estuary/ui/blob/0f4e1645a6a11de756722c9f99c523cf0665d212/src/types/index.ts#L55-L59), which suggests that we care about:
  * `image` (string): I assume this is a URL for the logo/connector image, and not the docker image?
  * `title` (string): I assume this is the human-readable name of this connector
  * `recommended` (boolean|null): Is this the field we were talking about that lets us hide non-production-ready connectors? Should we invert its meaning and call it `hidden` instead?
* In addition to the above fields, do we want to preemptively add `description` (string) in order to more closely match the UI on the marketing site?
* Where should these fields go? We seem to have `connectors` and `connector_tags`... and it's not clear which of them is right. `connectors` currently has the opengraph column(s), so on the one hand I could see adding these columns there, but `connector_tags` has `documentation_url`, which makes me think that maybe we'd actually want these other metadata to be tied to the tag (which I assume is used to represent the version of the connector), which would allow you to do things like change the description when you push a new version, or something like that.

**Comment by jgraettinger** [comment]
`image`, `title`, `description`, and (for just a couple of connectors) `recommended`, which is used to promote / list certain connectors first.

 A nice aspect of the current design is that it supports multiple languages, which we may want to continue to support. Perhaps we should just migrate by making the existing `open_graph` column non-generated and dropping `open_graph_raw` / `open_graph_patch`.
 
`documentation_url` should perhaps also migrate to `connectors`. What's a bit odd about these is that the connector _tells_ us what its documentation URL is going to be, and _technically_ different versions of the connector could have different documentation URLs. However in practice I think we always just want to keep the most recent.
